-- Create email_settings table
CREATE TABLE IF NOT EXISTS email_settings (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    is_active BOOLEAN DEFAULT true,
    min_profit_sek INTEGER DEFAULT 200,
    min_discount INTEGER DEFAULT 15,
    PRIMARY KEY (id)
);

-- Insert default row if not exists
INSERT INTO email_settings (is_active, min_profit_sek, min_discount)
VALUES (true, 200, 15)
ON CONFLICT DO NOTHING;
