-- Create save_settings table
CREATE TABLE IF NOT EXISTS save_settings (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    min_confidence INTEGER DEFAULT 0,
    value INTEGER DEFAULT 500,
    min_ads INTEGER DEFAULT 10,
    PRIMARY KEY (id)
);

-- Insert default row if not exists
INSERT INTO save_settings (min_confidence, value, min_ads)
VALUES (0, 500, 10)
ON CONFLICT DO NOTHING;
