-- Create economy_settings table
CREATE TABLE IF NOT EXISTS economy_settings (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    turnover_days INTEGER DEFAULT 30,
    PRIMARY KEY (id)
);

-- Insert default row if not exists
INSERT INTO economy_settings (turnover_days)
VALUES (30)
ON CONFLICT DO NOTHING;
