-- Create auto_enable_settings table
CREATE TABLE IF NOT EXISTS auto_enable_settings (
    id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    min_confidence INTEGER DEFAULT 90,
    value INTEGER DEFAULT 500,
    PRIMARY KEY (id)
);

-- Insert default row if not exists
INSERT INTO auto_enable_settings (min_confidence, value)
VALUES (90, 500)
ON CONFLICT DO NOTHING;
