DROP TABLE IF EXISTS search_criteria;
DROP TABLE IF EXISTS search_terms;

CREATE TABLE IF NOT EXISTS "search_terms" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "marketplace_id" SMALLINT NOT NULL,
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY("id")
);

ALTER TABLE "search_terms"
ADD FOREIGN KEY("marketplace_id") REFERENCES "marketplaces"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE INDEX "idx_search_terms_active"
ON "search_terms" ("is_active");

CREATE INDEX "idx_search_terms_marketplace_id"
ON "search_terms" ("marketplace_id");
