CREATE TABLE IF NOT EXISTS "search_terms" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "query" TEXT NOT NULL,
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "search_criteria" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "search_term_id" INTEGER NOT NULL,
    "marketplace_id" SMALLINT NOT NULL,
    "max_price" INTEGER,
    "min_condition" SMALLINT,
    "extra_params" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY("id")
);

ALTER TABLE "search_criteria"
ADD FOREIGN KEY("search_term_id") REFERENCES "search_terms"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "search_criteria"
ADD FOREIGN KEY("marketplace_id") REFERENCES "marketplaces"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE INDEX "idx_search_terms_active"
ON "search_terms" ("is_active");

CREATE INDEX "idx_search_criteria_term_id"
ON "search_criteria" ("search_term_id");

CREATE INDEX "idx_search_criteria_marketplace_id"
ON "search_criteria" ("marketplace_id");
