CREATE TABLE IF NOT EXISTS "products" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "brand" TEXT,
    "name" TEXT,
    "sell_packaging_cost" INTEGER DEFAULT 0,
    "sell_postage_cost" INTEGER DEFAULT 0,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "colors" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "conditions" (
    "id" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "title" TEXT NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "trade_statuses" (
    "id" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "marketplaces" (
    "id" SMALLINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT,
    "link" TEXT,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "transaction_types" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "transactions" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "date" TIMESTAMPTZ DEFAULT NOW(),
    "amount" INTEGER,
    "transaction_type" INTEGER,
    PRIMARY KEY("id")
);

CREATE INDEX "idx_transactions_type"
ON "transactions" ("transaction_type");

CREATE TABLE IF NOT EXISTS "trading_rules" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "min_profit_sek" INTEGER,
    "min_discount" SMALLINT,
    PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "traded_items" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "product_id" INTEGER,
    "storage" SMALLINT,
    "color_id" INTEGER,
    "buy_price" INTEGER,
    "buy_shipping_cost" INTEGER DEFAULT 0,
    "buy_transaction_id" INTEGER,
    "buy_date" TIMESTAMPTZ,
    "sell_price" INTEGER,
    "sell_packaging_cost" INTEGER DEFAULT 0,
    "sell_postage_cost" INTEGER DEFAULT 0,
    "sell_shipping_collected" INTEGER DEFAULT 0,
    "sell_transaction_id" INTEGER,
    "sell_date" TIMESTAMPTZ,
    "status_id" SMALLINT DEFAULT 1,
    "source_link" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "listing_id" INTEGER,
    PRIMARY KEY("id")
);

CREATE INDEX "idx_traded_items_status_id"
ON "traded_items" ("status_id");

CREATE TABLE IF NOT EXISTS "listings" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "product_id" INTEGER,
    "price" INTEGER,
    "link" TEXT,
    "condition_id" SMALLINT,
    "shipping_cost" SMALLINT,
    "description" TEXT,
    "marketplace_id" SMALLINT,
    "status" TEXT DEFAULT 'draft',
    "publication_date" TIMESTAMPTZ,
    "sold_date" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "is_my_listing" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY("id")
);

CREATE INDEX "idx_listings_product_id"
ON "listings" ("product_id");
CREATE INDEX "idx_listings_status"
ON "listings" ("status");
CREATE INDEX "idx_listings_marketplace_id"
ON "listings" ("marketplace_id");

CREATE TABLE IF NOT EXISTS "image_links" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "url" TEXT,
    "listing_id" INTEGER,
    PRIMARY KEY("id")
);

CREATE INDEX "idx_image_links_listing_id"
ON "image_links" ("listing_id");

INSERT INTO "trade_statuses" ("id", "name") VALUES
    (1, 'potential'),
    (2, 'purchased'),
    (3, 'in_stock'),
    (4, 'listed'),
    (5, 'sold')
ON CONFLICT ("id") DO NOTHING;

ALTER TABLE "traded_items"
ADD FOREIGN KEY("product_id") REFERENCES "products"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "traded_items"
ADD FOREIGN KEY("status_id") REFERENCES "trade_statuses"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "traded_items"
ADD FOREIGN KEY("listing_id") REFERENCES "listings"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "listings"
ADD FOREIGN KEY("product_id") REFERENCES "products"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "listings"
ADD FOREIGN KEY("condition_id") REFERENCES "conditions"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "listings"
ADD FOREIGN KEY("marketplace_id") REFERENCES "marketplaces"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "transactions"
ADD FOREIGN KEY("transaction_type") REFERENCES "transaction_types"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "image_links"
ADD FOREIGN KEY("listing_id") REFERENCES "listings"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
